export const apiEndpoint = {
  prefix: "/api",
  userRegister: "/auth/user/register",
  userLogin: "/auth/user/login",
  employerRegister: "/auth/employer/register",
  employerLogin: "/auth/employer/login",
  authMe: "/auth/me",
  authLogout: "/auth/logout",
  adminLogin: "/admin/login",
  adminLogout: "/admin/logout",
  adminMe: "/admin/me",
  adminJobSeekers: "/admin/job-seekers",
  adminJobSeekerById: "/admin/job-seekers/:id",
  adminJobSeekerPassword: "/admin/job-seekers/:id/password",
  adminJobSeekerStatus: "/admin/job-seekers/:id/status",
  adminEmployers: "/admin/employers",
  adminEmployerById: "/admin/employers/:id",
  adminEmployerPassword: "/admin/employers/:id/password",
  adminEmployerStatus: "/admin/employers/:id/status",
  adminJobListings: "/admin/job-listings",
  adminJobListingById: "/admin/job-listings/:id",
  adminJobListingStatus: "/admin/job-listings/:id/status",
  adminApplications: "/admin/applications",
  adminApplicationById: "/admin/applications/:id",
  adminApplicationStatus: "/admin/applications/:id/status",
  adminDashboardStats: "/admin/dashboard/stats",
  adminDashboardRecentJobs: "/admin/dashboard/recent-jobs",
  adminDashboardRecentApplications: "/admin/dashboard/recent-applications",
};

export const appRoutes = {
  home: "/",
  about: "/about",
  contact: "/contact",
  jobs: "/jobs",
  jobDetails: "/jobs/:id",
  jobSeekers: "/job-seekers",
  employers: "/employers/:id",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  adminLogin: "/admin/login",
  adminDashboard: "/admin/dashboard",
  adminJobSeekers: "/admin/job-seekers",
  adminEmployers: "/admin/employers",
  adminJobListings: "/admin/job-listings",
  adminApplications: "/admin/applications",
  userLogin: "/user/login",
  userRegister: "/user/register",
  userDashboard: "/user/dashboard",
  userProfile: "/user/profile",
  userApplications: "/user/applications",
  userApplicationDetails: "/user/applications/:id",
  userSavedJobs: "/user/saved-jobs",
  userSettings: "/user/settings",
  userNotifications: "/user/notifications",
  employerLogin: "/employer/login",
  employerRegister: "/employer/register",
  employerDashboard: "/employer/dashboard",
  employerProfile: "/employer/profile",
  employerJobs: "/employer/jobs",
  employerJobCreate: "/employer/jobs/create",
  employerJobDetails: "/employer/jobs/:id",
  employerJobEdit: "/employer/jobs/:id/edit",
  employerJobApplications: "/employer/jobs/:id/applications",
  employerApplications: "/employer/applications",
  employerApplicationDetails: "/employer/applications/:id",
  employerSettings: "/employer/settings",
};

export function replacePathParams(
  path: string,
  params: Record<string, string>,
): string {
  return Object.entries(params).reduce(
    (acc, [key, value]) => acc.replace(`:${key}`, encodeURIComponent(value)),
    path,
  );
}
